version = "3.0"
license = "LGPL-3"
date = "01 September 2016"
package = "luccme"
title = "LuccME"
url = "http://luccme.ccst.inpe.br/"
authors = "CCST - INPE"
contact = "luccme@inpe.br"
content = [[LuccME version 3.0 implementation.]]
