version = "3.0"
license = "LGPL-3"
date = "15 March 2016"
package = "luccme"
title = ""
url = "http://luccme.ccst.inpe.br/"
authors = "INPE"
contact = "luccme@inpe.br"
content = [[LuccME version 3.0 implementation.]]
